services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    hostname: reverse_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./log:/var/log/nginx
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl

    networks:
      webserver-net:
        ipv4_address: 10.20.10.10
      app-net:
        ipv4_address: 10.10.10.40
networks:
  webserver-net:
    external: true
  app-net:
    external: true
